openapi: 3.0.0
info:
  title: Cat Database API
  version: '1.0'
servers:
  - url: 'http://127.0.0.1:3000'
paths:
  /cats:
    get:
      summary: Get a paginated list of cats
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatListResponse'
        '500':
          description: Internal Server Error
    post:
      summary: Add a new cat to the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cat'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /cats/{breed}:
    get:
      summary: Get cats by breed
      parameters:
        - name: breed
          in: path
          description: Breed of the cat to be retrieved
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cat'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    put:
      summary: Update existing cat's details
      parameters:
        - name: breed
          in: path
          description: Breed of the cat to be updated
          required: true
          schema:
            type: string
        - name: Cat
          in: body
          description: Updated Cat object
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cat'
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    delete:
      summary: Delete a cat from the database
      parameters:
        - name: breed
          in: path
          description: Breed of the cat to be deleted
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
        '500':
          description: Internal Server Error

components:
  schemas:
    Cat:
      type: object
      properties:
        id:
          type: string
        breed:
          type: string
        name:
          type: string
        age:
          type: integer
      required:
        - id
        - breed
        - name

    CatListResponse:
      type: object
      properties:
        Items:
          type: array
          items:
            $ref: '#/components/schemas/Cat'
        LastEvaluatedKey:
          type: object
          description: Last evaluated key for pagination
